/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package player;

/**
 *
 * @author Amninder Singh
 */
public class Gener {
    private final static String[] genres = {
          "Blues"
	, "Classic Rock"
	, "Country"
	, "Dance"
	, "Disco"
	, "Funk"
	, "Grunge"
	, "Hip-Hop"
	, "Jazz"
	, "Metal"
	, "New Age"
	, "Oldies"
	, "Other"
	, "Pop"
	, "R&B"
	, "Rap"
	, "Reggae"
	, "Rock"
	, "Techno"
	, "Industrial"
	, "Alternative"
	, "Ska"
	, "Death Metal"
	, "Pranks"
	, "Soundtrack"
	, "Euro-Techno"
	, "Ambient"
	, "Trip-Hop"
	, "Vocal"
	, "Jazz+Funk"
	, "Fusion"
	, "Trance"
	, "Classical"
	, "Instrumental"
	, "Acid"
	, "House"
	, "Game"
	, "Sound Clip"
	, "Gospel"
	, "Noise"
	, "AlternRock"
	, "Bass"
	, "Soul"
	, "Punk"
	, "Space"
	, "Meditative"
	, "Instrumental Pop"
	, "Instrumental Rock"
	, "Ethnic"
	, "Gothic"
	, "Darkwave"
	, "Techno-Industrial"
	, "Electronic"
	, "Pop-Folk"
	, "Eurodance"
	, "Dream"
	, "Southern Rock"
	, "Comedy"
	, "Cult"
	, "Gangsta"
	, "Top 40"
	, "Christian Rap"
	, "Pop/Funk"
	, "Jungle"
	, "Native American"
	, "Cabaret"
	, "New Wave"
	, "Psychadelic"
	, "Rave"
	, "Showtunes"
	, "Trailer"
	, "Lo-Fi"
	, "Tribal"
	, "Acid Punk"
	, "Acid Jazz"
	, "Polka"
	, "Retro"
	, "Musical"
	, "Rock & Roll"
	, "Hard Rock"
	, "Folk"
	, "Folk-Rock"
	, "National Folk"
	, "Swing"
	, "Fast Fusion"
	, "Bebob"
	, "Latin"
	, "Revival"
	, "Celtic"
	, "Bluegrass"
	, "Avantgarde"
	, "Gothic Rock"
	, "Progressive Rock"
	, "Psychedelic Rock"
	, "Symphonic Rock"
	, "Slow Rock"
	, "Big Band"
	, "Chorus"
	, "Easy Listening"
	, "Acoustic"
	, "Humour"
	, "Speech"
	, "Chanson"
	, "Opera"
	, "Chamber Music"
	, "Sonata"
	, "Symphony"
	, "Booty Brass"
	, "Primus"
	, "Porn Groove"
	, "Satire"
	, "Slow Jam"
	, "Club"
	, "Tango"
	, "Samba"
	, "Folklore"
	, "Ballad"
	, "Power Ballad"
	, "Rhythmic Soul"
	, "Freestyle"
	, "Duet"
	, "Punk Rock"
	, "Drum Solo"
	, "A Capela"
	, "Euro-House"
	, "Dance Hall" 
    };
    public static String getGenre(int genreCODE)
    {
        String str;
        if((genreCODE<genres.length)&&(genreCODE>=0))
        {
            str=genres[genreCODE];
        }
        else
        {
            str="Genre Not Defined";
        }
        return str;
    }

}
